# Change these first
owner: acdh-oeaw # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: ACDH-CH shared assets
    url: https://shared.acdh.oeaw.ac.at/test.html
  - name: ARCHE
    url: https://arche.acdh.oeaw.ac.at/browser/
  - name: Baserow
    url: https://baserow.acdh-dev.oeaw.ac.at/
  - name: DHCR
    url: https://dhcr.clarin-dariah.eu
  - name: IIIF server
    url: https://iiif.acdh.oeaw.ac.at/iiif/images/wpn/0293.jp2/full/max/0/default.jpg
  - name: Mattermost
    url: https://mattermost.acdh.oeaw.ac.at/login
  - name: PMB    
    url: https://pmb.acdh.oeaw.ac.at/
  - name: Rancher
    url: https://rancher.acdh-dev.oeaw.ac.at/
  - name: OEAW Resources
    url: https://www.oeaw.ac.at/resources/
  - name: Redmine
    url: https://redmine.acdh.oeaw.ac.at/
  - name: SSHOC Marketplace API
    url: https://marketplace-api.sshopencloud.eu/api/property-types
  - name: Teach DARIAH
    url: https://teach.dariah.eu/course/index.php
  - name: Triplestore
    url: https://triplestore.acdh-dev.oeaw.ac.at/bgherkules/
    expectedStatusCodes:
      - 401
  - name: Typesense
    url: https://typesense.acdh-dev.oeaw.ac.at/health
  - name: Vocabs
    url: https://vocabs.acdh.oeaw.ac.at/en/
  - name: Imprint
    url: https://imprint.acdh.oeaw.ac.at
  - name: Viewer
    url: https://viewer.acdh.oeaw.ac.at
  - name: Austria Media Corpus (AMC)
    url: https://noske-amc.acdh.oeaw.ac.at/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.acdh-dev.oeaw.ac.at # will forward, so does not do what we want
  baseUrl: /status
  logoUrl: https://www.oeaw.ac.at/fileadmin/oeaw/institutstemplate/acdh/img/acdh-ch-logo96.png
  name: ACDH-CH
  introTitle: "ACDH-CH uptime status page"
  introMessage: This is uptime status page of ACDH-CH core services 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
