# Change these first
owner: acdh-oeaw # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: ARCHE
    url: https://arche.acdh.oeaw.ac.at/browser/
  - name: Baserow
    url: https://baserow.acdh-dev.oeaw.ac.at/
  - name: OEAW Resources
    url: https://www.oeaw.ac.at/resources/
  - name: Typesense
    url: https://typesense.acdh-dev.oeaw.ac.at/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://www.oeaw.ac.at/fileadmin/oeaw/institutstemplate/acdh/img/acdh-ch-logo96.png
  name: ACDH-CH
  introTitle: "ACDH-CH uptime status page"
  introMessage: This is uptime status page of ACDH-CH core services 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
